/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import AppShell from "../components/AppShell";
import api from "../utils/api";
const blankUser = { name: "", email: "", password: "", role: "user", address: "" };
export default function AdminConsole() {
  const navigate = useNavigate();
  const [stats, setStats] = useState({ totalUsers: 0, totalStores: 0, totalRatings: 0, flaggedReviews: 0, pendingStores: 0 });
  const [users, setUsers] = useState([]); const [stores, setStores] = useState([]); const [categories, setCategories] = useState([]); const [flagged, setFlagged] = useState([]);
  const [query, setQuery] = useState(""); const [modal, setModal] = useState(""); const [form, setForm] = useState(blankUser);
  const [detail, setDetail] = useState(null); const [msg, setMsg] = useState(""); const [newCat, setNewCat] = useState("");
  const load = async () => { try { const r = await Promise.all([api.get("/admin/dashboard"), api.get("/admin/users", { params: { q: query } }), api.get("/admin/stores", { params: { q: query } }), api.get("/categories"), api.get("/admin/reviews/flagged")]); setStats(r[0].data); setUsers(r[1].data.users); setStores(r[2].data); setCategories(r[3].data); setFlagged(r[4].data); } catch (e) { setMsg(e.response?.data?.message || "Could not load administrator data."); } };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); try { await api.post("/admin/add-user", form); setMsg("User created."); setModal(""); setForm(blankUser); load(); } catch (e) { setMsg(e.response?.data?.errors?.[0]?.msg || e.response?.data?.message || "Could not save record."); } };
  const openDetail = async (id) => { try { setDetail((await api.get(`/admin/users/${id}`)).data); } catch { setMsg("Could not load user details."); } };
  const toggleUser = async (id) => { try { const r = await api.put(`/admin/users/${id}/suspend`); setMsg(r.data.message); load(); } catch (e) { setMsg(e.response?.data?.message || "Could not update user."); } };
  const setStoreApproval = async (id, isApproved) => { try { const r = await api.put(`/admin/stores/${id}/status`, { isApproved }); setMsg(r.data.message); load(); } catch (e) { setMsg(e.response?.data?.message || "Could not update store."); } };
  const toggleStoreSuspend = async (id, isSuspended) => { try { const r = await api.put(`/admin/stores/${id}/status`, { isSuspended }); setMsg(r.data.message); load(); } catch (e) { setMsg(e.response?.data?.message || "Could not update store."); } };
  const rejectStore = async (id) => { try { const r = await api.delete(`/admin/stores/${id}`); setMsg(r.data.message); load(); } catch (e) { setMsg(e.response?.data?.message || "Could not remove store."); } };
  const addCategory = async () => { if (!newCat.trim()) return; try { await api.post("/admin/categories", { name: newCat }); setMsg("Category added."); setNewCat(""); load(); } catch (e) { setMsg(e.response?.data?.message || "Could not add category."); } };
  const deleteCategory = async (id) => { try { await api.delete(`/admin/categories/${id}`); setMsg("Category deleted."); load(); } catch (e) { setMsg(e.response?.data?.message || "Could not delete category."); } };
  const deleteReview = async (id) => { try { await api.delete(`/admin/reviews/${id}`); setMsg("Review deleted."); load(); } catch (e) { setMsg(e.response?.data?.message || "Could not delete review."); } };
  const clearFlag = async (id) => { try { const r = await api.post(`/admin/reviews/${id}/clear-flag`); setMsg(r.data.message); load(); } catch (e) { setMsg(e.response?.data?.message || "Could not clear flag."); } };
  const tabs = [["users", "People"], ["stores", "Stores"], ["pending", "Pending"], ["categories", "Categories"], ["reported", "Reported reviews"]];
  const pendingList = stores.filter((s) => !s.isApproved && !s.isSuspended);
  const storeRowProps = { onApprove: setStoreApproval, onToggleSuspend: toggleStoreSuspend, onDelete: (id) => { if (window.confirm("Reject and permanently remove this store listing?")) rejectStore(id); }, onEdit: (id) => navigate(`/admin/edit-store/${id}`) };
  // Sidebar "People & stores" switches views via URL hash. React Router's
  // navigate() uses pushState and never fires the native `hashchange` event,
  // so the hash is read reactively from useLocation() instead.
  const location = useLocation();
  const hash = location.hash.replace("#", "");
  const tab = tabs.some(([k]) => k === hash) ? hash : "users";
  const isOverview = !hash || hash === "overview";
  const goTab = (key) => navigate(`/admin/dashboard#${key}`, { replace: true });
  useEffect(() => { window.scrollTo({ top: 0, behavior: "smooth" }); }, [hash]);
  return <AppShell role="admin" title="Platform administration" subtitle="Monitor your community, manage accounts and stores, and moderate reviews.">
    {isOverview && <div className="metrics"><Metric label="Total users" value={stats.totalUsers} /><Metric label="Listed stores" value={stats.totalStores} /><Metric label="Pending approval" value={stats.pendingStores} /><Metric label="Ratings" value={stats.totalRatings} /><Metric label="Reported" value={stats.flaggedReviews} /></div>}
    {msg && <p className="notice success">{msg}</p>}
    <section className="section"><div className="section-title"><h2>Management</h2><div className="tools">{tabs.map(([key, label]) => <button key={key} className={tab === key ? "primary-btn" : "secondary-btn"} onClick={() => goTab(key)}>{key === "pending" ? `${label}${pendingList.length ? ` (${pendingList.length})` : ""}` : label}</button>)}</div></div>
      <div className="tools" style={{ marginBottom: 14 }}><input className="table-search" placeholder="Search people or stores" value={query} onChange={(event) => setQuery(event.target.value)} /><button className="secondary-btn" onClick={load}>Search</button>{tab === "users" && <button className="primary-btn" onClick={() => { setForm(blankUser); setModal("user"); }}>Add user</button>}{tab === "stores" && <button className="primary-btn" onClick={() => navigate("/admin/add-store")}>Add store</button>}</div>
      {tab === "users" && <UsersTable users={users} onDetail={openDetail} onSuspend={toggleUser} />}
      {tab === "stores" && <StoresTable stores={stores} {...storeRowProps} />}
      {tab === "pending" && (pendingList.length ? <StoresTable stores={pendingList} {...storeRowProps} /> : <div className="empty">No stores waiting for approval. Stores that owners register or claim will appear here for review.</div>)}
      {tab === "categories" && <CategoriesPanel categories={categories} newCat={newCat} setNewCat={setNewCat} onAdd={addCategory} onDelete={deleteCategory} />}
      {tab === "reported" && <ReportedPanel flagged={flagged} onDelete={deleteReview} onClear={clearFlag} />}
    </section>
    {modal === "user" && <UserForm form={form} setForm={setForm} close={() => setModal("")} submit={submit} />}
    {detail && <UserDetailModal detail={detail} close={() => setDetail(null)} />}
  </AppShell>;
}
function Metric({ label, value }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function UsersTable({ users, onDetail, onSuspend }) { return <div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody>{users.map((u) => <tr key={u.id}><td><strong>{u.name}</strong><br /><small>{u.address || "No address"}</small></td><td>{u.email}</td><td><span className={`badge ${u.role}`}>{u.role}</span></td><td>{u.isSuspended ? <span className="badge">Suspended</span> : <span className="badge owner">Active</span>}</td><td><div className="review-actions"><button className="secondary-btn" onClick={() => onDetail(u.id)}>Details</button>{u.role !== "admin" ? <button className={u.isSuspended ? "secondary-btn" : "danger-btn"} onClick={() => onSuspend(u.id)}>{u.isSuspended ? "Re-activate" : "Suspend"}</button> : <span className="badge owner">Protected</span>}</div></td></tr>)}</tbody></table></div>; }
function StoresTable({ stores, onApprove, onToggleSuspend, onDelete, onEdit }) { return <div className="table-wrap"><table className="data-table"><thead><tr><th>Store</th><th>Category</th><th>Rating</th><th>Status</th><th></th></tr></thead><tbody>{stores.map((s) => <tr key={s.id}><td><strong>{s.name}</strong><br /><small>{s.address || "No address"}</small></td><td>{s.category || "—"}</td><td>{s.avgRating ? `${s.avgRating.toFixed(1)} (${s.ratingCount})` : "—"}</td><td>{s.isSuspended ? <span className="badge">Suspended</span> : s.isApproved ? <span className="badge owner">Approved</span> : <span className="badge">Pending</span>}</td><td><div className="review-actions"><button className="secondary-btn" onClick={() => onEdit(s.id)}>Edit</button>{!s.isApproved && !s.isSuspended && <><button className="secondary-btn" onClick={() => onApprove(s.id, true)}>Approve</button><button className="danger-btn" onClick={() => onDelete(s.id)}>Reject</button></>}<button className={s.isSuspended ? "secondary-btn" : "danger-btn"} onClick={() => onToggleSuspend(s.id, !s.isSuspended)}>{s.isSuspended ? "Unsuspend" : "Suspend"}</button></div></td></tr>)}</tbody></table></div>; }
function CategoriesPanel({ categories, newCat, setNewCat, onAdd, onDelete }) { return <div><div className="tools" style={{ marginBottom: 14 }}><input className="table-search" placeholder="New category name…" value={newCat} onChange={(event) => setNewCat(event.target.value)} /><button className="primary-btn" onClick={onAdd}>Add category</button></div>{categories.map((c) => <div className="list-item" key={c.id}><strong>{c.name}</strong><button className="danger-btn" onClick={() => onDelete(c.id)}>Delete</button></div>)}</div>; }
function ReportedPanel({ flagged, onDelete, onClear }) { return flagged.length ? <div>{flagged.map((r) => <div className="review-item" key={r.id}><div className="review-head"><strong>{r.user ? r.user.name : "Customer"}</strong><span className="stars">{"★".repeat(r.rating)}{"☆".repeat(5 - r.rating)}</span></div><p className="muted">{r.store ? r.store.name : "Store"} · {new Date(r.createdAt).toLocaleDateString()}</p>{r.review && <p>{r.review}</p>}<div className="review-actions"><button className="secondary-btn" onClick={() => onClear(r.id)}>Keep (clear flag)</button><button className="danger-btn" onClick={() => onDelete(r.id)}>Delete review</button></div></div>)}</div> : <div className="empty">No reported reviews right now.</div>; }

function UserForm({ form, setForm, close, submit }) { const update = (event) => setForm({ ...form, [event.target.name]: event.target.value }); return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><h2>Add user</h2><p className="muted">Create a new account.</p><label className="field">Name<input name="name" value={form.name} onChange={update} required /></label><label className="field">Email<input name="email" type="email" value={form.email} onChange={update} required /></label><label className="field">Password<input name="password" type="password" minLength="4" value={form.password} onChange={update} required /></label><label className="field">Role<select name="role" value={form.role} onChange={update}><option value="user">User</option><option value="owner">Store owner</option><option value="admin">Administrator</option></select></label><label className="field">Address<input name="address" value={form.address} onChange={update} /></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={close}>Cancel</button><button className="primary-btn">Create user</button></div></form></div>; }
function UserDetailModal({ detail, close }) { const { user, ownerRating } = detail; const ownedStore = user.Stores?.[0]; return <div className="modal-backdrop"><div className="modal"><h2>User details</h2><p className="muted">Account profile.</p><div className="list-item"><span>Name</span><strong>{user.name}</strong></div><div className="list-item"><span>Email</span><strong>{user.email}</strong></div><div className="list-item"><span>Phone</span><strong>{user.phone || "Not provided"}</strong></div><div className="list-item"><span>Role</span><span className={`badge ${user.role}`}>{user.role}</span></div><div className="list-item"><span>Address</span><strong>{user.address || "Not provided"}</strong></div><div className="list-item"><span>Status</span><strong>{user.isSuspended ? "Suspended" : "Active"}</strong></div>{ownedStore && <><div className="list-item"><span>Assigned store</span><strong>{ownedStore.name}</strong></div><div className="list-item"><span>Store average</span><strong>{ownerRating ? `${ownerRating.toFixed(1)} / 5` : "No ratings yet"}</strong></div></>}<div className="modal-actions"><button className="primary-btn" onClick={close}>Close</button></div></div></div>; }

