/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect, useState } from "react";
import AppShell from "../components/AppShell";
import api from "../utils/api";

const blankUser = { name: "", email: "", address: "", password: "", role: "user" };
const blankStore = { name: "", email: "", address: "", ownerId: "" };

export default function AdminDashboard() {
  const [stats, setStats] = useState({ totalUsers: 0, totalStores: 0, totalRatings: 0 });
  const [users, setUsers] = useState([]); const [stores, setStores] = useState([]);
  const [query, setQuery] = useState(""); const [modal, setModal] = useState("");
  const [form, setForm] = useState(blankUser); const [detail, setDetail] = useState(null);
  const [message, setMessage] = useState(""); const [isSaving, setIsSaving] = useState(false);
  const load = async () => { try { const [dashboard, people, listedStores] = await Promise.all([api.get("/admin/dashboard"), api.get("/admin/users", { params: { q: query } }), api.get("/admin/stores", { params: { q: query } })]); setStats(dashboard.data); setUsers(people.data.users); setStores(listedStores.data); } catch (error) { setMessage(error.response?.data?.message || "Could not load administrator data."); } };
  useEffect(() => { load(); }, []);
  const openDetail = async (id) => { try { const response = await api.get(`/admin/users/${id}`); setDetail(response.data); } catch (error) { setMessage(error.response?.data?.message || "Could not load user details."); } };
  const submit = async (event) => { event.preventDefault(); setIsSaving(true); try { const payload = modal === "store" ? { ...form, ownerId: form.ownerId || undefined } : form; await api.post(modal === "user" ? "/admin/add-user" : "/admin/add-store", payload); setMessage(`${modal === "user" ? "User" : "Store"} created successfully.`); setModal(""); setForm(blankUser); load(); } catch (error) { setMessage(error.response?.data?.errors?.[0]?.msg || error.response?.data?.message || "Could not save this record."); } finally { setIsSaving(false); } };
  return <AppShell role="admin" active="overview" title="Operations overview" subtitle="Manage people, stores, and the health of your rating community.">
    <div id="overview" className="metrics"><Metric label="Total users" value={stats.totalUsers} /><Metric label="Listed stores" value={stats.totalStores} /><Metric label="Ratings submitted" value={stats.totalRatings} /></div>
    {message && <p className="notice success">{message}</p>}
    <section id="users" className="section"><div className="section-title"><div><h2>People & stores</h2><p className="muted">Select a user to view their complete account profile.</p></div><div className="tools"><input className="table-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search people or stores" /><button className="secondary-btn" onClick={load}>Search</button><button className="primary-btn" onClick={() => { setForm(blankUser); setModal("user"); }}>Add user</button><button className="primary-btn" onClick={() => { setForm(blankStore); setModal("store"); }}>Add store</button></div></div>
      <div className="split"><DataTable title="People" heads={["Name", "Email", "Role", "Actions"]}>{users.map((user) => <tr key={user.id}><td><strong>{user.name}</strong><br /><small>{user.address || "No address"}</small></td><td>{user.email}</td><td><RoleBadge role={user.role} /></td><td><button className="secondary-btn" onClick={() => openDetail(user.id)}>View details</button></td></tr>)}</DataTable><DataTable title="Stores" heads={["Store", "Rating", "Reviews", "Address"]}>{stores.map((store) => <tr key={store.id}><td><strong>{store.name}</strong><br /><small>{store.email || "No email"}</small></td><td>{store.avgRating ? store.avgRating.toFixed(1) : "—"} / 5</td><td>{store.ratingCount}</td><td>{store.address || "—"}</td></tr>)}</DataTable></div>
    </section>
    <section id="settings" className="section"><h2>Administrator tools</h2><p className="muted">Use the People & stores panel to add records, assign a store owner, search records, and inspect full user details.</p></section>
    {modal && <RecordModal type={modal} form={form} setForm={setForm} users={users} close={() => setModal("")} submit={submit} saving={isSaving} />}
    {detail && <UserDetail detail={detail} close={() => setDetail(null)} />}
  </AppShell>;
}
function Metric({ label, value }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function RoleBadge({ role }) { return <span className={`badge ${role}`}>{role}</span>; }
function DataTable({ title, heads, children }) { return <div><h3>{title}</h3><div className="table-wrap"><table className="data-table"><thead><tr>{heads.map((head) => <th key={head}>{head}</th>)}</tr></thead><tbody>{children}</tbody></table></div></div>; }
function RecordModal({ type, form, setForm, users, close, submit, saving }) { const update = (event) => setForm({ ...form, [event.target.name]: event.target.value }); return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><h2>Add {type === "user" ? "user" : "store"}</h2><p className="muted">Create a new {type} record.</p><label className="field">{type === "user" ? "Full name" : "Store name"}<input name="name" value={form.name} onChange={update} required /></label>{type === "user" && <><label className="field">Email<input name="email" type="email" value={form.email} onChange={update} required /></label><label className="field">Password<input name="password" type="password" minLength="4" value={form.password} onChange={update} required /></label><label className="field">Role<select name="role" value={form.role} onChange={update}><option value="user">User</option><option value="owner">Store owner</option><option value="admin">Administrator</option></select></label></>}{type === "store" && <><label className="field">Contact email <span className="muted">(optional)</span><input name="email" type="email" value={form.email} onChange={update} /></label><label className="field">Owner <span className="muted">(optional)</span><select name="ownerId" value={form.ownerId} onChange={update}><option value="">No owner assigned</option>{users.filter((user) => user.role === "owner").map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label></>}<label className="field">Address<input name="address" value={form.address} onChange={update} required={type === "store"} /></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={close}>Cancel</button><button className="primary-btn" disabled={saving}>{saving ? "Saving…" : `Create ${type}`}</button></div></form></div>; }
function UserDetail({ detail, close }) { const { user, ownerRating } = detail; const ownedStore = user.Stores?.[0]; return <div className="modal-backdrop"><div className="modal"><h2>User details</h2><p className="muted">Account profile and store assignment.</p><div className="list-item"><span>Name</span><strong>{user.name}</strong></div><div className="list-item"><span>Email</span><strong>{user.email}</strong></div><div className="list-item"><span>Role</span><RoleBadge role={user.role} /></div><div className="list-item"><span>Address</span><strong>{user.address || "Not provided"}</strong></div>{ownedStore && <><div className="list-item"><span>Assigned store</span><strong>{ownedStore.name}</strong></div><div className="list-item"><span>Store average</span><strong>{ownerRating ? `${ownerRating.toFixed(1)} / 5` : "No ratings yet"}</strong></div></>}<div className="modal-actions"><button className="primary-btn" onClick={close}>Close</button></div></div></div>; }