import { useState } from "react";
import api from "../utils/api";
import { Link, useNavigate } from "react-router-dom";

export default function Register() {
  const [form, setForm] = useState({ name: "", email: "", phone: "", address: "", password: "", role: "user", storeName: "", storeAddress: "" });
  const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  const update = (e) => setForm({ ...form, [e.target.name]: e.target.value });
  const submit = async (e) => { e.preventDefault(); setError(""); if (form.role === "owner" && !form.storeName.trim()) return setError("Store name is required for store owners."); setLoading(true); try { await api.post("/auth/register", form); navigate("/", { state: { message: "Account created. Please sign in." } }); } catch (err) { setError(err.response?.data?.errors?.[0]?.msg || err.response?.data?.message || "Registration failed. Please try again."); } finally { setLoading(false); } };
  return <div className="auth-page"><section className="auth-hero"><div><div className="brand"><span className="brand-mark">S</span>StoreScope</div><h1>Put your store on the map.</h1><p>Create a member account to rate stores, or register as an owner to follow your store’s feedback.</p></div><div className="auth-points"><span>Free to join</span><span>One account</span><span>Real feedback</span></div></section><main className="auth-panel"><form className="auth-card" onSubmit={submit}><h2>Create account</h2><p className="muted">Join the StoreScope community.</p>{error && <p className="notice error">{error}</p>}<label className="field">Full name<input name="name" value={form.name} onChange={update} required maxLength="60" /></label><label className="field">Email<input name="email" type="email" value={form.email} onChange={update} required /></label><label className="field">Phone <span className="muted">(optional)</span><input name="phone" value={form.phone} onChange={update} maxLength="40" /></label><label className="field">Address <span className="muted">(optional)</span><input name="address" value={form.address} onChange={update} /></label><label className="field">Password<input name="password" type="password" value={form.password} onChange={update} minLength="4" required /></label><label className="field">I am joining as<select name="role" value={form.role} onChange={update}><option value="user">A customer</option><option value="owner">A store owner</option></select></label>{form.role === "owner" && <><label className="field">Store name<input name="storeName" value={form.storeName} onChange={update} required /></label><label className="field">Store address<input name="storeAddress" value={form.storeAddress} onChange={update} /></label></>}<button className="primary-btn full" disabled={loading}>{loading ? "Creating account…" : "Create account"}</button><p className="muted" style={{marginTop:20}}>Already registered? <Link to="/" className="form-link">Sign in</Link></p></form></main></div>;
}